---
default_language_version:
  python: python3.10
exclude: .venv
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.4.0
    hooks:
      - id: ansible-lint
        files: \.yml$

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.2.2
    hooks:
      - id: ansible_role_find_unused_variable
      - id: ansible_role_find_empty_files
      - id: ansible_role_find_empty_directories

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5  # or specific git tag
    hooks:
      - id: shellcheck
