---

- name: Set java_top
  become: yes
  set_fact:
    java8_top: '/usr/lib/jvm'
  tags:
    - java8
    - java8_install
    - java8_profile
    - java8_test
    - java8_alternatives
    - test
    - config
    - ant_test
    - maven_test
    - gradle_test

- name: What java8_rpms
  when: ansible_os_family == 'RedHat'
  debug:
    msg: "{{ java8_rpms }}"

- name: Ensure Java is installed.
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ java8_rpms }}"
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2

- name: Ensure file is installed for tests
  when: ansible_os_family == 'RedHat'
  yum:
    name: file
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2

- name: What java8_apt
  when: ansible_os_family == 'Debian'
  debug:
    msg: "{{ java8_apt }}"

- name: Ensure python-apt is installed.
  when: ansible_os_family == 'Debian'
  apt:
    name: python-apt
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2

- name: Update apt cache.
  when: ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - java8
    - java8_install

- name: Ensure Java is installed.
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ java8_apt }}"
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay:

- name: Make sure java_top exists
  become: yes
  file:
    path: "{{ java8_top }}"
    state: directory
    owner: root
    mode: 0755
  tags:
    - java8

- name: This is JAVA_HOME
  when: ansible_os_family == 'RedHat'
  set_fact:
    java8_home: "{{ java8_top }}/java"
  tags:
    - config
    - java8
    - java8_test
    - test
    - ant_test
    - maven_test
    - gradle_test

- name: This is JAVA_HOME
  when: ansible_os_family == 'Debian'
  set_fact:
    java8_home: "{{ java8_top }}/{{ ubuntu_dir }}"
  tags:
    - config
    - java8
    - java8_test
    - test
    - ant_test
    - maven_test
    - gradle_test

- name: Ensure facts can be stored locally
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - java8
    - config

- name: Install java8 facts
  template:
    src: java8.fact
    dest: /etc/ansible/facts.d/java8.fact
    owner: root
    group: root
    mode: 0644
  tags:
    - java8
    - config

- name: Copy test_java.yml to remote
  template:
    src: test_java.yml.j2
    dest: /root/test_java.yml
  tags:
    - java8
    - java8_profile
    - test
    - config

- name: Fix JAVA_HOME
  become: yes
  template:
    src: java.sh
    dest: /etc/profile.d/java.sh
  tags:
    - config
    - java8
    - java8_profile

- name: ensure directory exists
  file:
    path: /root
    state: directory
    owner: root
    group: root
    mode: 0700
  tags:
    - java8
    - java8_profile
    - test
    - config
