---

- name: install on Linux
  include_tasks: linux.yml
  when:
    - ansible_os_family != 'Windows'
    - ansible_os_family != 'Darwin'
  tags:
    - linux

- name: install on Windows
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags:
    - windows
...
