---
# Standards: 0.2
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-java8-centos7
    image: centos:7
    privileged: true
  - name: base-java8-xenial
    image: ubuntu:xenial
    privileged: true
  - name: base-java8-bionic
    image: ubuntu:bionic
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
