---
# Standards: 0.2
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-java8-centos7
    image: centos:7
    privileged: True
  - name: base-java8-centos6
    image: centos:6
    privileged: true
  - name: base-java8-ubuntu
    image: ubuntu
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
