---
# Standards: 0.2
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later
platforms:
  - name: base-java8-centos8
    image: quay.io/centos/centos:stream8
    privileged: true
  - name: base-java8-centos7
    image: centos:7
    privileged: true
  - name: base-java8-focal
    image: ubuntu:focal
    privileged: true
  - name: base-java8-bionic
    image: ubuntu:bionic
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
