---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: setup
      become: false
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - './Whoami.java'
        - './Whoami.class'
      tags:
        - java8
        - java8_test
        - test

    - name: smoke test java runtime
      become: false
      command: "java -version"
      changed_when: false
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      register: java
      tags:
        - java8
        - java8_test
        - test

    - name: log java version
      become: false
      debug:
        msg: "java ?? {{ java.stderr }}"
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      tags:
        - java8
        - java8_test
        - test

    - name: copy java source for tests
      become: false
      copy:
        src: tests/Whoami.java
        dest: /tmp
        mode: 0644
      changed_when: false
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      tags:
        - java8
        - java8_test
        - test

    - name: functional test Java compiler
      become: false
      command: "javac /tmp/Whoami.java"
      register: java_compile
      changed_when: false
      failed_when: "java_compile.rc != 0"
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      tags:
        - java8
        - java8_test
        - test

    - name: functional test Java runtime
      become: false
      command: "java -cp /tmp Whoami"
      changed_when: false
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      register: java8_class
      tags:
        - java8
        - java8_test
        - test

    - name: verify bytecode version
      become: false
      command: "file /tmp/Whoami.class"
      changed_when: false
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      register: java8_class
      tags:
        - java8
        - java8_test
        - test

    - name: display bytecode version
      become: false
      debug:
        msg: "{{ java8_class.stdout_lines }}"
      ignore_errors: "{{ continue_on_error | default(true, true) }}"
      tags:
        - java8
        - java8_test
        - test

    - name: teardown
      become: false
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - '/tmp/Whoami.java'
        - '/tmp/Whoami.class'
      changed_when: false
      tags:
        - java8
        - java8_test
        - test
